version: '3.8'

services:
  # client:
  #   build:
  #     context: ./
  #     dockerfile: client/Dockerfile
  #   ports:
  #     - "80:80"
  #   restart: unless-stopped
  #   networks:
  #     - app-network

  server:
    build:
      context: ./
      dockerfile: server/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
